### ISSUE TITLE
Redis Server Crash reconnect error?

### ISSUE THREAD

**Issue by mllongze** [LewisJEllis/bee-queue#24]
Hello @LewisJEllis  :alien:
> <h3>test the code below to my local project </h3>

```javascript
 var job = queue.createJob({name: "test"}).save();
        job.on('succeeded', function (result) {
            console.log('Received result for job ' + job.id + ': result : ' + JSON.stringify(result));
        })
        queue.on('error', function (err) {
            console.log("queue all error show -- ", err);
        });
        queue.process(function (job, done) {
            //do ... ing
            return done(null, job.data);
        });
```

>  <h3>stop redis server</h3>

```javascript
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
```

> <h3>restart redis server</h3>

>  <h3>execute code again </h3>

```javascript
/Users/xxxx/node-project/socket/node_modules/bee-queue/node_modules/redis/index.js:578
                throw callback_err;
                      ^
Error: NOSCRIPT No matching script. Please use EVAL.
    at ReplyParser.<anonymous> (/Users/xxxx/node-project/socket/node_modules/bee-queue/node_modules/redis/index.js:320:31)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_error (/Users/xxx/node-project/socket/node_modules/bee-queue/node_modules/redis/lib/parser/javascript.js:298:10)
    at ReplyParser.execute (/Users/xxxx/node-project/socket/node_modules/bee-queue/node_modules/redis/lib/parser/javascript.js:183:22)
    at RedisClient.on_data (/Users/xxxx/node-project/socket/node_modules/bee-queue/node_modules/redis/index.js:550:27)
    at Socket.<anonymous> (/Users/xxxx/node-project/socket/node_modules/bee-queue/node_modules/redis/index.js:105:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by mllongze** [comment]
Hi  @LewisJEllis  

I think i find the question!

because client.evalsha is rebuild cache when redis server restart.

so i fixed it.  add [flushCache, buildCache] on client "ready"。

the flushCache only like this
```javascript
delete cachedServers[serverKey]; 
```

I don't know this change will not have a problem!

**Comment by LewisJEllis** [comment]
Oh, hmm. I know restarting Redis clears the script cache, which we depend on having populated on bee-queue startup. I suppose if we just clear it on a restart then bee-queue will repopulate the cache.

**Comment by LewisJEllis** [comment]
Oh, yep, roughly that is exactly the fix I was just describing. If you want to send a PR, I'll verify it and publish a new version to npm.

**Comment by mllongze** [comment]
@LewisJEllis
 Thank you for your answer. 
 I looking forward for you add cluster.
 I will always focus on the project. :smiley:

**Comment by davisford** [comment]
I'm seeing the same problem on localhost redis 3.0.3.  I am working on migrating some code from kue to bee-queue, and when I start the app up, I hit this exact exception.  

I'm not sure I follow the recommended fix above -- can someone clarify?

**Comment by LewisJEllis** [comment]
Yes, I can do that fix and publish a new version to npm tonight. I originally wanted to give @mllongze time to send a PR since he originally found the fix, but it's been long enough.
